services:
  #PHP Service
  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
      - XDEBUG_MODE=debug
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./Docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 8000:8000
    depends_on:
      - database
      - database_testing
      - redis
    entrypoint:
      - Docker/entrypoint.sh
    labels:
      - "XDEBUG_CONFIG=remote_host=host.docker.internal remote_port=9000"

  # Database Server
  database:
    image: mysql:8.2
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 3306:3306
    command: --default-authentication-plugin=caching_sha2_password
    env_file:
      - .env
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./Docker/my.cnf:/etc/mysql/my.cnf

  database_testing:
    image: mysql:8.2
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 3307:3306
    command: --default-authentication-plugin=caching_sha2_password
    env_file:
      - .env.testing
    environment:
      - MYSQL_HOST=database_testing
      - MYSQL_ROOT_HOST=database_testing
      - MYSQL_DATABASE=tech_blog_testing
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-test-data:/var/lib/mysql

  #Redis Server
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - 6379:6379

  #Queue Server
  queue:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=queue
    working_dir: /var/www
    volumes:
      - ./:/var/www


  #Node
  node:
    build:
      context: .
      target: node
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - ./node_modules:/usr/src/node_modules
    tty: true

networks:
  default:
    driver: bridge

volumes:
  db-data: ~
  db-test-data: ~
